# © 2025 EcoHub AG. All rights reserved.
# Publicly accessible for informational purposes only.
# No rights to use, implement, modify, reproduce, distribute, or create derivative works without prior written authorization.
# Swiss law applies. Jurisdiction: Zurich.

openapi: 3.0.1
info:
  title: 'SAF Kafka REST Proxy API'
  version: 1.1.0
  x-ecohub-license: >
    © 2025 EcoHub AG. Usage restricted. Prior written authorization required. Swiss law applies.
  contact:
    email: support@myecohub.ch
    name: EcoHub AG
    url: 'https://www.myecohub.ch'
  description: >
    The SAF Kafka REST Proxy provides a RESTful interface to the Kafka cluster, making it easy to produce and consume 
    messages.
    
    ### Security

    All endpoints are protected and a TechUser certificate (mTLS) or 
    bearer token must be provided. The certificate or oAuth2 credentials can be acquired using 
    the /techUserEnrolment endpoint of the General API.
    
    ### Changes in Version 1.1.0
      - Improved documentation
      - ProcessNameType
        - renamed the enum values for proxy standards. These values were not yet used on the platform, therefore this change is treated as MINOR, not MAJOR.
        - added enum values for remaining legacy standards
      - SubProcessNameType
        - renamed the enum values for proxy standards. These values were not yet used on the platform, therefore this change is treated as MINOR, not MAJOR.
        - added enum values for remaining legacy standards 
      - added endpoint to consume commission topic
      - added endpoint to consume invoice topic
      - added endpoint to consume contract topic
      - added endpoint to consume mandate topic
      - added endpoint to consume claimsExperience topic
      
    
    *changes in previous versions are available in the changelog file in GitHub*
servers:
  - url: 'https://services.test-myecohub.ch/saf/v1'
  - url: 'https://services.myecohub.ch/saf/v1'
paths:
  /in:
    post:
      tags:
        - Producing Messages
      summary: Post an event to the SAF Message Broker
      description: Post an event to the SAF Message Broker
      operationId: post-eh-saf-in
      parameters:
        - name: schemaVersionId
          in: header
          description: The id of the schema which is used to serialize the event value
          schema:
            type: integer
            enum: [ 100044 ]
          required: true
        - name: keySchemaVersionId
          in: header
          description: The id of the schema which is used to serialize the event key
          schema:
            type: integer
            enum: [ 100021 ]
          required: true
        - name: Content-Type
          in: header
          required: true
          schema:
            enum:
              - application/json
            type: string
            default: application/json
      requestBody:
        description: The event to be produced.
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/SAFEventType'
                - $ref: '#/components/schemas/SAFInquiryEventType'
                - $ref: '#/components/schemas/SAFErrorEventType'
                - $ref: '#/components/schemas/OfferNLPIErrorEventType'
            examples:
              eventWithPayloadExample:
                summary: SAFEvent with offer.nlpi payload
                value:
                  id: 044d2e50-12d6-43e4-bb1b-7b54841c9c82
                  source: http://www.myecohub.ch/ecoHub-mock-broker-producer1
                  specversion: '1.0'
                  type: ch.ecohub.saf.data
                  datacontenttype: application/json
                  dataschema: https://raw.githubusercontent.com/EcoHub-AG/Standards/refs/tags/Offer_NLPI_v0.3.0/schemas/Offer-NLPI/v0.3.0/offer-nlpi-root/OfferNlpiRequestDataType.json
                  subject: offer nlpi request
                  time: '2023-08-17T14:15:22.000Z'
                  licenceKey: REcxZEVMZWV1UXFwOUZwaz...
                  userAgent:
                    name: BS1
                    version: '1.0'
                  eventReceiver:
                    category: insurer
                    id: IDP1234567
                  eventSender:
                    category: broker
                    id: IDP7654321
                  data:
                    payload: V2UgZGlkbid0IGluY2x1ZGUgdGhlIGZ1bGwgcGF5bG9hZCBoZ...
                    payloadSignature: MEYCIQD76gKbAynmvE5Ndq+Tnnf/aBziZlryXkP
                    encryptionKey: urpx9D/0MwvQoCz3nNcQyMpEh2VEW6X7TiMmIfH...
                    publicKeyVersion: '1.1'
                    signatureKeyVersion: '1.3'
                  processId: ff9275bf-5b35-492e-bdd2-c217e151d335
                  processName: offer.nlpi
                  processVersion: 0.3.0
                  processStatus: active
                  subProcessName: request
                  subProcessStatus: Created
              acknowledgeEventExample:
                summary: Acknowledge Event
                value:
                  id: 044d2e50-12d6-43e4-bb1b-7b54841c9c82
                  source: http://www.myecohub.ch/ecoHub-mock-broker-producer1
                  specversion: '1.0'
                  type: ch.ecohub.saf.data
                  subject: offer nlpi request acknowledgement
                  time: '2023-08-17T14:15:22.000Z'
                  licenceKey: REcxZEVMZWV1UXFwOUZwaz...
                  userAgent:
                    name: BS1
                    version: '1.0'
                  eventReceiver:
                    category: insurer
                    id: IDP1234567
                  eventSender:
                    category: broker
                    id: IDP7654321
                  processId: ff9275bf-5b35-492e-bdd2-c217e151d335
                  processName: offer.nlpi
                  processVersion: 0.3.0
                  processStatus: active
                  subProcessName: request
                  subProcessStatus: Received
      responses:
        '200':
          description: Returns EventResponseType
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventResponseType'
        '400':
          description: Bad request. Input data is not valid.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseType'
              example:
                error_code: 400
                message: 'Bad Request: #: #: 0 subschemas matched instead of one'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneralErrorResponseType'
              example:
                statusCode: 401
                message: 'Invalid Azure AD JWT'
        '404':
          description: Resource not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseType'
              example:
                error_code: 400
                message: 'Resource not found'
        '500':
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneralErrorResponseType'
              example:
                statusCode: 500
                message: 'Internal server error'
                activityId: 'e4ab80c8-1fdf-4ee8-8a74-68d114cbcbed'
  '/{ecohubId}/offer/nlpi/out':
    get:
      tags:
        - Consuming Messages
      summary: Consume messages from the offer.nlpi topic.
      description: Returns unread messages from the offer.nlpi topic.
      operationId: get-eh-saf-ecohubid-offer-nlpi-out
      parameters:
        - name: ecohubId
          in: path
          description: >-
            The EcoHubId can be looked up in EcoHub on the Standard API
            Framework configuration page.
          required: true
          schema:
            type: string
        - name: auto.offset.reset
          in: header
          description: The auto offset that should be used to retrieve records
          required: true
          schema:
            enum:
              - earliest
              - latest
            type: string
      responses:
        '200':
          description: "All unread messages in the topic"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TopicResponseType'
              example:
                - topic: eh.saf.329050.offer.nlpi.out.v1
                  key:
                    processId: 'ff9275bf-5b35-492e-bdd2-c217e151d335'
                  value:
                    id: 044d2e50-12d6-43e4-bb1b-7b54841c9c82
                    source: http://www.myecohub.ch/ecoHub-mock-broker-producer1
                    specversion: '1.0'
                    type: ch.ecohub.saf.data
                    datacontenttype: application/json
                    dataschema: https://raw.githubusercontent.com/EcoHub-AG/Standards/refs/tags/offer-nlpi-v0.6.0/schemas/Offer-NLPI/v0.6.0/offer-nlpi-root/OfferNlpiRequestDataType.json
                    subject: offer nlpi request
                    time: '2023-08-17T14:15:22.000Z'
                    licenceKey: REcxZEVMZWV1UXFwOUZwaz...
                    userAgent:
                      name: BS1
                      version: '1.0'
                    eventReceiver:
                      category: insurer
                      id: IDP1234567
                    eventSender:
                      category: broker
                      id: IDP7654321
                    data:
                      payload: V2UgZGlkbid0IGluY2x1ZGUgdGhlIGZ1bGwgcGF5bG9hZCBoZ...
                      payloadSignature: MEYCIQD76gKbAynmvE5Ndq+Tnnf/aBziZlryXkP
                      encryptionKey: urpx9D/0MwvQoCz3nNcQyMpEh2VEW6X7TiMmIfH...
                      publicKeyVersion: '1.1'
                      signatureKeyVersion: '1.3'
                    processId: ff9275bf-5b35-492e-bdd2-c217e151d335
                    processName: offer.nlpi
                    processVersion: 0.6.0
                    processStatus: active
                    subProcessName: request
                    subProcessStatus: Created
                  partition: 1
                  offset: 4
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneralErrorResponseType'
              example:
                statusCode: 401
                message: 'Invalid Azure AD JWT'
        403:
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseType'
              example:
                error_code: 40301
                message: 'Not authorized to access topics: [eh.saf.329050.offer.nlpi.out.v1]'
  '/{ecohubId}/commission/out':
    get:
      tags:
        - Consuming Messages
      summary: Consume messages from the commission topic.
      description: Returns unread mesassages from the commission topic
      operationId: get-eh-saf-ecohubid-commission-out
      parameters:
        - name: ecohubId
          in: path
          description: >-
            The EcoHubId can be looked up in EcoHub on the Standard API
            Framework configuration page.
          required: true
          schema:
            type: string
        - name: auto.offset.reset
          in: header
          description: The auto offset that should be used to retrieve records
          required: true
          schema:
            enum:
              - earliest
              - latest
            type: string
      responses:
        '200':
          description: "All unread messages in the topic"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TopicResponseType'
              example:
                - topic: eh.saf.329050.commission.out.v1
                  key:
                    processId: 'ff9275bf-5b35-492e-bdd2-c217e151d335'
                  value:
                    id: 044d2e50-12d6-43e4-bb1b-7b54841c9c82
                    source: http://www.myecohub.ch/ecoHub-mock-broker-producer1
                    specversion: '1.0'
                    type: ch.ecohub.saf.data
                    datacontenttype: application/json
                    dataschema: https://raw.githubusercontent.com/EcoHub-AG/Standards/refs/tags/commission-v5.4.1/schemas/legacy/5.4.1/commission_V5.4.1.xsd
                    subject: Commission Documents
                    time: '2023-08-17T14:15:22.000Z'
                    licenceKey: REcxZEVMZWV1UXFwOUZwaz...
                    userAgent:
                      name: Insurer Backend Software 1
                      version: '1.0'
                    eventReceiver:
                      category: broker
                      id: IDP1234567
                    eventSender:
                      category: insurer
                      id: IDP7654321
                    data:
                      payload: V2UgZGlkbid0IGluY2x1ZGUgdGhlIGZ1bGwgcGF5bG9hZCBoZ...
                      payloadSignature: MEYCIQD76gKbAynmvE5Ndq+Tnnf/aBziZlryXkP
                      encryptionKey: urpx9D/0MwvQoCz3nNcQyMpEh2VEW6X7TiMmIfH...
                      publicKeyVersion: '1.1'
                      signatureKeyVersion: '1.3'
                    processId: ff9275bf-5b35-492e-bdd2-c217e151d335
                    processName: commission
                    processVersion: 5.4.1
                    processStatus: closed
                    subProcessName: commission
                    subProcessStatus: Created
                  partition: 1
                  offset: 4
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneralErrorResponseType'
              example:
                statusCode: 401
                message: 'Invalid Azure AD JWT'
        403:
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseType'
              example:
                error_code: 40301
                message: 'Not authorized to access topics: [eh.saf.329050.commission.out.v1]'
  '/{ecohubId}/invoice/out':
    get:
      tags:
        - Consuming Messages
      summary: Consume messages from the invoice topic.
      description: Returns unread messages from the invoice topic
      operationId: get-eh-saf-ecohubid-invoice-out
      parameters:
        - name: ecohubId
          in: path
          description: >-
            The EcoHubId can be looked up in EcoHub on the Standard API
            Framework configuration page.
          required: true
          schema:
            type: string
        - name: auto.offset.reset
          in: header
          description: The auto offset that should be used to retrieve records
          required: true
          schema:
            enum:
              - earliest
              - latest
            type: string
      responses:
        '200':
          description: "All unread messages in the topic"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TopicResponseType'
              example:
                - topic: eh.saf.329050.invoice.out.v1
                  key:
                    processId: 'ff9275bf-5b35-492e-bdd2-c217e151d335'
                  value:
                    id: 044d2e50-12d6-43e4-bb1b-7b54841c9c82
                    source: http://www.myecohub.ch/ecoHub-mock-broker-producer1
                    specversion: '1.0'
                    type: ch.ecohub.saf.data
                    datacontenttype: application/json
                    dataschema: https://raw.githubusercontent.com/EcoHub-AG/Standards/refs/tags/invoice-v5.4.1/schemas/legacy/5.4.1/billing_V5.4.1.xsd
                    subject: Billing Documents
                    time: '2023-08-17T14:15:22.000Z'
                    licenceKey: REcxZEVMZWV1UXFwOUZwaz...
                    userAgent:
                      name: Insurer Backend Software 1
                      version: '1.0'
                    eventReceiver:
                      category: broker
                      id: IDP1234567
                    eventSender:
                      category: insurer
                      id: IDP7654321
                    data:
                      payload: V2UgZGlkbid0IGluY2x1ZGUgdGhlIGZ1bGwgcGF5bG9hZCBoZ...
                      payloadSignature: MEYCIQD76gKbAynmvE5Ndq+Tnnf/aBziZlryXkP
                      encryptionKey: urpx9D/0MwvQoCz3nNcQyMpEh2VEW6X7TiMmIfH...
                      publicKeyVersion: '1.1'
                      signatureKeyVersion: '1.3'
                    processId: ff9275bf-5b35-492e-bdd2-c217e151d335
                    processName: invoice
                    processVersion: 5.4.1
                    processStatus: closed
                    subProcessName: billing
                    subProcessStatus: Created
                  partition: 1
                  offset: 4
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneralErrorResponseType'
              example:
                statusCode: 401
                message: 'Invalid Azure AD JWT'
        403:
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseType'
              example:
                error_code: 40301
                message: 'Not authorized to access topics: [eh.saf.329050.invoice.out.v1]'
  '/{ecohubId}/contract/out':
    get:
      tags:
        - Consuming Messages
      summary: Consume messages from the contract topic.
      description: Returns unread messages from the contract topic
      operationId: get-eh-saf-ecohubid-contract-out
      parameters:
        - name: ecohubId
          in: path
          description: >-
            The EcoHubId can be looked up in EcoHub on the Standard API
            Framework configuration page.
          required: true
          schema:
            type: string
        - name: auto.offset.reset
          in: header
          description: The auto offset that should be used to retrieve records
          required: true
          schema:
            enum:
              - earliest
              - latest
            type: string
      responses:
        '200':
          description: "All unread messages in the topic"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TopicResponseType'
              example:
                - topic: eh.saf.329050.contract.out.v1
                  key:
                    processId: 'ff9275bf-5b35-492e-bdd2-c217e151d335'
                  value:
                    id: 044d2e50-12d6-43e4-bb1b-7b54841c9c82
                    source: http://www.myecohub.ch/ecoHub-mock-broker-producer1
                    specversion: '1.0'
                    type: ch.ecohub.saf.data
                    datacontenttype: application/json
                    dataschema: https://raw.githubusercontent.com/EcoHub-AG/Standards/refs/tags/contract-v5.4.1/schemas/legacy/5.4.1/contractGeneric_V5.4.1.xsd
                    subject: Policy Documents
                    time: '2023-08-17T14:15:22.000Z'
                    licenceKey: REcxZEVMZWV1UXFwOUZwaz...
                    userAgent:
                      name: Insurer Backend Software 1
                      version: '1.0'
                    eventReceiver:
                      category: broker
                      id: IDP1234567
                    eventSender:
                      category: insurer
                      id: IDP7654321
                    data:
                      payload: V2UgZGlkbid0IGluY2x1ZGUgdGhlIGZ1bGwgcGF5bG9hZCBoZ...
                      payloadSignature: MEYCIQD76gKbAynmvE5Ndq+Tnnf/aBziZlryXkP
                      encryptionKey: urpx9D/0MwvQoCz3nNcQyMpEh2VEW6X7TiMmIfH...
                      publicKeyVersion: '1.1'
                      signatureKeyVersion: '1.3'
                    processId: ff9275bf-5b35-492e-bdd2-c217e151d335
                    processName: contract
                    processVersion: 5.4.1
                    processStatus: closed
                    subProcessName: contract
                    subProcessStatus: Created
                  partition: 1
                  offset: 4
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneralErrorResponseType'
              example:
                statusCode: 401
                message: 'Invalid Azure AD JWT'
        403:
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseType'
              example:
                error_code: 40301
                message: 'Not authorized to access topics: [eh.saf.329050.contract.out.v1]'
  '/{ecohubId}/mandate/out':
    get:
      tags:
        - Consuming Messages
      summary: Consume messages from the mandate topic.
      description: Returns unread messages from the mandate topic
      operationId: get-eh-saf-ecohubid-mandate-out
      parameters:
        - name: ecohubId
          in: path
          description: >-
            The EcoHubId can be looked up in EcoHub on the Standard API
            Framework configuration page.
          required: true
          schema:
            type: string
        - name: auto.offset.reset
          in: header
          description: The auto offset that should be used to retrieve records
          required: true
          schema:
            enum:
              - earliest
              - latest
            type: string
      responses:
        '200':
          description: "All unread messages in the topic"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TopicResponseType'
              example:
                - topic: eh.saf.329050.mandate.out.v1
                  key:
                    processId: 'ff9275bf-5b35-492e-bdd2-c217e151d335'
                  value:
                    id: 044d2e50-12d6-43e4-bb1b-7b54841c9c82
                    source: http://www.myecohub.ch/ecoHub-mock-broker-producer1
                    specversion: '1.0'
                    type: ch.ecohub.saf.data
                    datacontenttype: application/json
                    dataschema: https://raw.githubusercontent.com/EcoHub-AG/Standards/refs/tags/mandate-v5.4.1/schemas/legacy/5.4.1/mandateFeedback_V5.4.1.xsd
                    subject: Mandate Feedback
                    time: '2023-08-17T14:15:22.000Z'
                    licenceKey: REcxZEVMZWV1UXFwOUZwaz...
                    userAgent:
                      name: Insurer Backend Software 1
                      version: '1.0'
                    eventReceiver:
                      category: broker
                      id: IDP1234567
                    eventSender:
                      category: insurer
                      id: IDP7654321
                    data:
                      payload: V2UgZGlkbid0IGluY2x1ZGUgdGhlIGZ1bGwgcGF5bG9hZCBoZ...
                      payloadSignature: MEYCIQD76gKbAynmvE5Ndq+Tnnf/aBziZlryXkP
                      encryptionKey: urpx9D/0MwvQoCz3nNcQyMpEh2VEW6X7TiMmIfH...
                      publicKeyVersion: '1.1'
                      signatureKeyVersion: '1.3'
                    processId: ff9275bf-5b35-492e-bdd2-c217e151d335
                    processName: mandate
                    processVersion: 5.4.1
                    processStatus: closed
                    subProcessName: feedback
                    subProcessStatus: Created
                  partition: 1
                  offset: 4
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneralErrorResponseType'
              example:
                statusCode: 401
                message: 'Invalid Azure AD JWT'
        403:
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseType'
              example:
                error_code: 40301
                message: 'Not authorized to access topics: [eh.saf.329050.mandate.out.v1]'
  '/{ecohubId}/claimsExperience/out':
    get:
      tags:
        - Consuming Messages
      summary: Consume messages from the claimsExperience topic.
      description: Returns unread messages from the claimsExperience topic
      operationId: get-eh-saf-ecohubid-claimsExperience-out
      parameters:
        - name: ecohubId
          in: path
          description: >-
            The EcoHubId can be looked up in EcoHub on the Standard API
            Framework configuration page.
          required: true
          schema:
            type: string
        - name: auto.offset.reset
          in: header
          description: The auto offset that should be used to retrieve records
          required: true
          schema:
            enum:
              - earliest
              - latest
            type: string
      responses:
        '200':
          description: "All unread messages in the topic"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TopicResponseType'
              example:
                - topic: eh.saf.329050.claimsExperience.out.v1
                  key:
                    processId: 'ff9275bf-5b35-492e-bdd2-c217e151d335'
                  value:
                    id: 044d2e50-12d6-43e4-bb1b-7b54841c9c82
                    source: http://www.myecohub.ch/ecoHub-mock-broker-producer1
                    specversion: '1.0'
                    type: ch.ecohub.saf.data
                    datacontenttype: application/json
                    dataschema: https://raw.githubusercontent.com/EcoHub-AG/Standards/refs/tags/claimsExperience-v5.4.1/schemas/legacy/5.4.1/claimsExperience_V5.4.1.xsd
                    subject: Claims Experience
                    time: '2023-08-17T14:15:22.000Z'
                    licenceKey: REcxZEVMZWV1UXFwOUZwaz...
                    userAgent:
                      name: Insurer Backend Software 1
                      version: '1.0'
                    eventReceiver:
                      category: broker
                      id: IDP1234567
                    eventSender:
                      category: insurer
                      id: IDP7654321
                    data:
                      payload: V2UgZGlkbid0IGluY2x1ZGUgdGhlIGZ1bGwgcGF5bG9hZCBoZ...
                      payloadSignature: MEYCIQD76gKbAynmvE5Ndq+Tnnf/aBziZlryXkP
                      encryptionKey: urpx9D/0MwvQoCz3nNcQyMpEh2VEW6X7TiMmIfH...
                      publicKeyVersion: '1.1'
                      signatureKeyVersion: '1.3'
                    processId: ff9275bf-5b35-492e-bdd2-c217e151d335
                    processName: claimsExperience
                    processVersion: 5.4.1
                    processStatus: closed
                    subProcessName: claimsExperience
                    subProcessStatus: Created
                  partition: 1
                  offset: 4
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneralErrorResponseType'
              example:
                statusCode: 401
                message: 'Invalid Azure AD JWT'
        403:
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseType'
              example:
                error_code: 40301
                message: 'Not authorized to access topics: [eh.saf.329050.claimsExperience.out.v1]'
components:
  schemas:
    SAFEventType:
      description: 'The main event type which can either be used to transmit business data according to a data standard or to send an acknowledge event.'
      type: object
      properties:
        id:
          $ref: '#/components/schemas/iddef'
        source:
          $ref: '#/components/schemas/sourcedef'
        specversion:
          $ref: '#/components/schemas/specversiondef'
        type:
          $ref: '#/components/schemas/EventType'
        datacontenttype:
          $ref: '#/components/schemas/datacontenttypedef'
        dataschema:
          $ref: '#/components/schemas/dataschemadef'
        subject:
          $ref: '#/components/schemas/subjectdef'
        time:
          $ref: '#/components/schemas/timedef'
        licenceKey:
          $ref: '#/components/schemas/LicenceKeyType'
        userAgent:
          $ref: '#/components/schemas/UserAgentType'
        eventReceiver:
          $ref: '#/components/schemas/SenderReceiverType'
        eventSender:
          $ref: '#/components/schemas/SenderReceiverType'
        data:
          $ref: '#/components/schemas/EventDataType'
        processGroupId:
          $ref: '#/components/schemas/ProcessGroupIdType'
        processId:
          $ref: '#/components/schemas/ProcessIdType'
        processName:
          $ref: '#/components/schemas/ProcessNameType'
        processVersion:
          $ref: '#/components/schemas/ProcessVersionType'
        processStatus:
          $ref: '#/components/schemas/ProcessStatusType'
        subProcessName:
          $ref: '#/components/schemas/SubProcessNameType'
        subProcessStatus:
          $ref: '#/components/schemas/SubProcessStatusType'
      additionalProperties: false
      required:
        - id
        - source
        - specversion
        - type
        - processId
        - processName
        - processVersion
        - subProcessName
        - processStatus
        - subProcessStatus
        - eventReceiver
        - eventSender
        - userAgent
        - licenceKey
    SAFInquiryEventType:
      description: 'SAF inquiry event, i.e. an event containing a generic message.'
      type: object
      properties:
        id:
          $ref: '#/components/schemas/iddef'
        source:
          $ref: '#/components/schemas/sourcedef'
        specversion:
          $ref: '#/components/schemas/specversiondef'
        type:
          $ref: '#/components/schemas/EventType'
        datacontenttype:
          $ref: '#/components/schemas/datacontenttypedef'
        dataschema:
          $ref: '#/components/schemas/dataschemadef'
        subject:
          $ref: '#/components/schemas/subjectdef'
        time:
          $ref: '#/components/schemas/timedef'
        licenceKey:
          $ref: '#/components/schemas/LicenceKeyType'
        userAgent:
          $ref: '#/components/schemas/UserAgentType'
        eventReceiver:
          $ref: '#/components/schemas/SenderReceiverType'
        eventSender:
          $ref: '#/components/schemas/SenderReceiverType'
        data:
          $ref: '#/components/schemas/EventMessageDataType'
        processGroupId:
          $ref: '#/components/schemas/ProcessGroupIdType'
        processId:
          $ref: '#/components/schemas/ProcessIdType'
        processName:
          $ref: '#/components/schemas/ProcessNameType'
        processVersion:
          $ref: '#/components/schemas/ProcessVersionType'
        processStatus:
          $ref: '#/components/schemas/ProcessStatusType'
        subProcessName:
          $ref: '#/components/schemas/SubProcessNameType'
        subProcessStatus:
          $ref: '#/components/schemas/SubProcessStatusType'
      additionalProperties: false
      required:
        - id
        - source
        - specversion
        - type
        - processId
        - processName
        - processVersion
        - subProcessName
        - processStatus
        - subProcessStatus
        - eventReceiver
        - eventSender
        - userAgent
        - licenceKey
    iddef:
      description: Identifies the event. Producers MUST ensure that source + id is unique
        for each distinct event. If a duplicate event is re-sent (e.g. due to a network
        error) it MAY have the same id. Consumers MAY assume that Events with identical
        source and id are duplicates.
      example: A234-1234-1234
      minLength: 1
      type: string
    sourcedef:
      description: Uniquely identifies the producer of the event. Must be globally unique,
        including across environments.
      example: http://www.myecohub.ch/iat/ecohub-processes | http://www.myecohub.ch/prod/ecohub-processes | http://www.myecohub.ch/ck/postman
      format: uri-reference
      minLength: 1
      type: string
    specversiondef:
      description: The version of the CloudEvents specification which the event uses. MUST
        be set to 1.0
      example: '1.0'
      minLength: 1
      type: string
    typedef:
      type: string
      minLength: 1
    datacontenttypedef:
      description: Content type of the data value. Must adhere to RFC 2046 format.
      example: text/xml | application/json
      minLength: 1
      type: string
    dataschemadef:
      description: Identifies the schema that data adheres to. Must point to the respective raw schema
        in the EcoHub GitHub schema repository (https://github.com/EcoHub-AG/Standards).
      format: uri
      minLength: 1
      type: string
      example:
        https://raw.githubusercontent.com/EcoHub-AG/Standards/refs/tags/Offer_NLPI_v0.3.0/schemas/Offer-NLPI/v0.3.0/offer-nlpi-root/OfferNlpiRequestDataType.json |
        https://raw.githubusercontent.com/EcoHub-AG/Standards/refs/tags/Offer_NLPI_v0.3.0/schemas/Offer-NLPI/v0.3.0/offer-nlpi-root/OfferNlpiDataType.json
    subjectdef:
      description: Describes the subject of the event to provide additional context about
        the event.
      example: Billing november 2024 | MF offer company A
      minLength: 1
      type: string
    timedef:
      description: Timestamp of when the occurrence happened. Must adhere to RFC 3339.
      example: '2018-04-05T17:31:00Z'
      format: date-time
      minLength: 1
      type: string
    EventDataType:
      description: The data transmitted with the event and relevant attributes for signing
        and encryption.
      type: object
      properties:
        payload:
          description: The base64 representation of the first g-zipped and then encrypted
            original payload. For encryption, the AES-GCM algorithm with a 256-bit key,
            a 96-bit initialization vector (IV), and a 128-bit authentication tag must be
            used.
          minLength: 3
          type: string
        payloadSignature:
          description: A digital signature used to verify the origin of the encrypted payload.
            The signature is created by signing the content of the payload attribute using
            the elliptic curve algorithm secp384r1 with a SHA-384 hash, and your active
            signature key. The resulting signature must be ASN.1 encoded and transmitted
            in Base64.
          minLength: 3
          type: string
        links:
          items:
            type: object
            properties:
              description:
                description: Description of the purpose of the link
                type: string
              href:
                description: the- encrypted URL that should be called, to receive additional
                  encrypted unstructured data, such as pdf, pictures, etc.
                example: https://services.test-myecohub.ch/offer/nlpi/{offerId}/{attachmentId}
                  (unencrypted example)
                minLength: 3
                type: string
              rel:
                description: The IG B2B Standard the links belongs to.
                example: offer-nlpi
                minLength: 3
                type: string
            required:
              - href
              - rel
            additionalProperties: false
          type: array
          minItems: 1
        encryptionKey:
          description: The encrypted AES key, which was used to symmetrically encrypt the
            transmitted data. The key must be encrypted with the public key of the eventReceiver
            using RSA with OAEP padding with a SHA256 hash.
          minLength: 3
          type: string
        publicKeyVersion:
          description: The version of the receiver's public key that was used to encrypt
            the encryptionKey.
          type: string
        signatureKeyVersion:
          description: The version of your signature key, that was used to sign the payload.
          type: string
      required:
        - payload
        - payloadSignature
        - encryptionKey
        - publicKeyVersion
        - signatureKeyVersion
      additionalProperties: false
    EventType:
      description: 'Reverse DNS entry to defines the type of event: data, inquiry, standard-error
        or saf-error'
      minLength: 1
      type: string
      enum:
        - ch.ecohub.saf.data
        - ch.ecohub.saf.inquiry
        - ch.ecohub.saf.standard-error
        - ch.ecohub.saf.saf-error
    LicenceKeyType:
      description: The license key for the requesting SC application.
      type: string
      maxLength: 200
      minLength: 3
      example: fdsaf346t54grthe65euz467jhz7r
    ProcessIdType:
      description: UUID, that won't change during the offer processes. The UUID is set by
        the party, that starts the process.
      type: string
      format: uuid
    ProcessNameType:
      description: Identifier of the core process
      type: string
      enum:
        - offer.nlpi
        - invoice
        - commission
        - contract
        - mandate
        - claimsExperience
    ProcessVersionType:
      description: Version of the used core process
      type: string
      pattern: "^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$"
    ProcessStatusType:
      description: Defines status of the overall process.
      type: string
      enum:
        - active
        - closed
    SenderReceiverType:
      type: object
      additionalProperties: false
      properties:
        category:
          description: The category of the organisation
          enum:
            - broker
            - insurer
            - serviceprovider
          example: broker
          type: string
        id:
          description: The IDP number of the member's techUser. The IDP number of the eventReceiver
            can be determined through the /saf-receivers endpoint of the General API.
          example: IDP1239856
          minLength: 3
          type: string
        onBehalfBy:
          type: string
          description: The IDP number of the software provider's techUser if the event is
            send on behalf.
          pattern: "^IDP(\\d{7})$"
      required:
        - category
        - id
    SubProcessNameType:
      description: Identifier for the current subprocess / process step within the core
        process.
      type: string
      enum:
        - request
        - offer
        - feedback
        - conclusionDecision
        - billing
        - reminder
        - contract
        - commission
        - submission
        - cancellation
        - claimsExperience
    SubProcessStatusType:
      type: string
      enum:
        - Created
        - Received
        - InProgress
        - Responded
        - Updated
        - Error
        - Inquiry
        - Inquiry_Answer
        - Closed
    UserAgentType:
      type: object
      description: Identifies the software that was used to produce the event
      properties:
        name:
          description: Name of the application
          example: Client software XYZ
          maxLength: 100
          minLength: 3
          type: string
        version:
          description: Used version of the application
          example: Version 1.0
          maxLength: 30
          minLength: 3
          type: string
      required:
        - name
        - version
      additionalProperties: false
    EventResponseType:
      type: object
      properties:
        key_schema_id:
          type: integer
          description: The ID for the schema used to produce keys, or null if keys were not used
        value_schema_id:
          type: integer
          description: The ID for the schema used to produce keys, or null if keys were not used
        offsets:
          type: array
          description: List of partitions and offsets the messages were published to
          items:
            type: object
            properties:
              partition:
                type: integer
                description: Partition the message was published to, or null if publishing the message failed
              offset:
                type: integer
                description: Offset of the message, or null if publishing the message failed
              error_code:
                type: integer
                description: An error code classifying the reason the operation failed, or null if it succeeded
                enum:
                  - 1
                  - 2
              error:
                type: string
                description: An error message describing why the operation failed, or null if it succeeded
    ErrorResponseType:
      type: object
      properties:
        error_code:
          type: integer
          description: HTTP status of the request
        message:
          type: string
          description: message describing the error
    GeneralErrorResponseType:
      type: object
      properties:
        statusCode:
          type: integer
          description: HTTP status of the request
        message:
          type: string
          description: message describing the error
        activityId:
          type: string
          description: Unique ID for the provided error message
          format: uuid
      additionalProperties: false
    EventMessageDataType:
      description: The message transmitted with the event and relevant attributes for signing
        and encryption.
      type: object
      properties:
        encryptionKey:
          description: The encrypted AES key, which was used to symmetrically encrypt the
            transmitted message. The key must be encrypted with the public key of the eventReceiver
            using RSA with OAEP padding with a SHA256 hash.
          minLength: 3
          type: string
        messageSignature:
          description: A digital signature used to verify the origin of the encrypted message.
            The signature is created by signing the content of the payload attribute using
            the elliptic curve algorithm secp384r1 with a SHA-384 hash, and your active
            signature key. The resulting signature must be ASN.1 encoded and transmitted
            in Base64.
          minLength: 3
          type: string
        message:
          description: The base64 representation of the first g-zipped and then encrypted
            original message. For encryption, the AES-GCM algorithm with a 256-bit key,
            a 96-bit initialization vector (IV), and a 128-bit authentication tag must be
            used.
          minLength: 3
          type: string
        publicKeyVersion:
          description: The version of the receiver's public key that was used to encrypt
            the encryptionKey.
          type: string
        signatureKeyVersion:
          description: The version of your signature key, that was used to sign the message.
          type: string
      required:
        - message
        - messageSignature
        - encryptionKey
        - publicKeyVersion
        - signatureKeyVersion
      additionalProperties: false
    SAFErrorEventType:
      description: SAF error event, i.e. an event for errors which are unrelated to the event payload.
      type: object
      properties:
        id:
          $ref: '#/components/schemas/iddef'
        source:
          $ref: '#/components/schemas/sourcedef'
        specversion:
          $ref: '#/components/schemas/specversiondef'
        type:
          $ref: '#/components/schemas/EventType'
        datacontenttype:
          $ref: '#/components/schemas/datacontenttypedef'
        dataschema:
          $ref: '#/components/schemas/dataschemadef'
        subject:
          $ref: '#/components/schemas/subjectdef'
        time:
          $ref: '#/components/schemas/timedef'
        licenceKey:
          $ref: '#/components/schemas/LicenceKeyType'
        userAgent:
          $ref: '#/components/schemas/UserAgentType'
        data:
          $ref: '#/components/schemas/ErrorDataType'
        eventReceiver:
          $ref: '#/components/schemas/SenderReceiverType'
        eventSender:
          $ref: '#/components/schemas/SenderReceiverType'
        processGroupId:
          $ref: '#/components/schemas/ProcessGroupIdType'
        processId:
          $ref: '#/components/schemas/ProcessIdType'
        processName:
          $ref: '#/components/schemas/ProcessNameType'
        processVersion:
          $ref: '#/components/schemas/ProcessVersionType'
        processStatus:
          $ref: '#/components/schemas/ProcessStatusType'
        subProcessName:
          $ref: '#/components/schemas/SubProcessNameType'
        subProcessStatus:
          $ref: '#/components/schemas/SubProcessStatusType'
      required:
        - id
        - source
        - specversion
        - type
        - processId
        - processName
        - processVersion
        - subProcessName
        - processStatus
        - subProcessStatus
        - eventReceiver
        - eventSender
        - userAgent
        - licenceKey
      additionalProperties: false
    ErrorDataType:
      description: The error event payload.
      type: object
      properties:
        errorCode:
          description: 'Categorizes the type of error'
          type: string
          minLength: 3
          enum:
            - licenseKey-not-valid
            - sa-not-found
            - receiver-not-found
            - event-not-valid
            - pk-version-not-found
            - data-content-invalid
            - data-schema-invalid
            - data-not-readable
            - data-decryption-failed
            - data-decompression-failed
            - other
        errorMessage:
          description: ""
          type: string
          minLength: 3
        errorDateTime:
          description: ""
          type: string
          format: date-time
      required:
        - errorCode
        - errorMessage
        - errorDateTime
    OfferNLPIErrorEventType:
      description: Offer NLPI error event, i.e. an event for errors which related to the
        event payload.
      type: object
      properties:
        id:
          $ref: '#/components/schemas/iddef'
        source:
          $ref: '#/components/schemas/sourcedef'
        specversion:
          $ref: '#/components/schemas/specversiondef'
        type:
          $ref: '#/components/schemas/EventType'
        datacontenttype:
          $ref: '#/components/schemas/datacontenttypedef'
        dataschema:
          $ref: '#/components/schemas/dataschemadef'
        subject:
          $ref: '#/components/schemas/subjectdef'
        time:
          $ref: '#/components/schemas/timedef'
        licenceKey:
          $ref: '#/components/schemas/LicenceKeyType'
        userAgent:
          $ref: '#/components/schemas/UserAgentType'
        data:
          $ref: '#/components/schemas/OfferNLPIErrorType'
        eventReceiver:
          $ref: '#/components/schemas/SenderReceiverType'
        eventSender:
          $ref: '#/components/schemas/SenderReceiverType'
        processGroupId:
          $ref: '#/components/schemas/ProcessGroupIdType'
        processId:
          $ref: '#/components/schemas/ProcessIdType'
        processName:
          $ref: '#/components/schemas/ProcessNameType'
        processVersion:
          $ref: '#/components/schemas/ProcessVersionType'
        processStatus:
          $ref: '#/components/schemas/ProcessStatusType'
        subProcessName:
          $ref: '#/components/schemas/SubProcessNameType'
        subProcessStatus:
          $ref: '#/components/schemas/SubProcessStatusType'
      required:
        - id
        - source
        - specversion
        - type
        - data
        - processId
        - processName
        - processVersion
        - subProcessName
        - processStatus
        - subProcessStatus
        - eventReceiver
        - eventSender
        - userAgent
        - licenceKey
      additionalProperties: false
    OfferNLPIErrorType:
      type: array
      minItems: 1
      items:
        type: object
        properties:
          errorCode:
            description: The code best describing the occured error.
            minLength: 3
            type: string
            enum:
              - other
          errorMessage:
            description: Error message
            minLength: 3
            type: string
          path:
            description: xPath or JsonPath to the property where the error occurred.
            type: string
        additionalProperties: false
        required:
          - errorCode
          - errorMessage
    ProcessGroupIdType:
      description: UUID, that is used to associate multiple processes. The exact usage is
        specified in each data standard.
      type: string
      format: uuid
    SAFKeyType:
      description: Format of the kafka message key
      type: object
      properties:
        processId:
          $ref: '#/components/schemas/ProcessIdType'
      additionalProperties: false
      required:
        - processId
    TopicResponseType:
      type: array
      items:
        type: object
        properties:
          topic:
            type: string
          key:
            $ref: '#/components/schemas/SAFKeyType'
          value:
            type: object
            oneOf:
              - $ref: '#/components/schemas/SAFEventType'
              - $ref: '#/components/schemas/SAFInquiryEventType'
              - $ref: '#/components/schemas/SAFErrorEventType'
              - $ref: '#/components/schemas/OfferNLPIErrorEventType'
          partition:
            type: integer
          offset:
            type: integer
        required:
          - topic
          - key
          - value
          - partition
          - offset

